package:
    name: openmdao.examples.expected_improvement
    version: dev
    
source:
    path: ../../examples/openmdao.examples.expected_improvement

build:
    preserve_egg_dir: yes
    
requirements:
    build:
        - python
        - setuptools
        - openmdao.main
        - openmdao.lib
    
    run:
        - python
        - setuptools
        - openmdao.main
        - openmdao.lib
