package:
 name: openmdao.util
 version: dev

source:
 path:  ../../openmdao.util

build:
    preserve_egg_dir: True
    
requirements:
  build:
    - python
    - setuptools
    - pycrypto
    - pyparsing
    - traits ==4.3.0

  run:
    - python
    - setuptools
    - pycrypto
    - pyparsing
    - traits ==4.3.0

build:
  entry_points:
    - xyplot = openmdao.util.casedb:cmdlineXYplot
    - plotgraph = openmdao.util.graphplot:main
    - dotgraph = openmdao.util.dotgraph:main
    - add_reqs = openmdao.util.addreqs:add_reqs
    - mkpseudo = openmdao.util.mkpseudo:mkpseudo
    - envdump = openmdao.util.envirodump:envdump
    - pstadump = openmdao.util.dep:main
    - update_libpath = openmdao.util.lib:update_libpath
    - combine_paths = openmdao.util.lib:combine_paths

about:
  home:  http://openmdao.org
  license:  Apache 2.0
  summary:  "Open-source Multidisciplinary Design, Analysis and Optimazation framework in Python."
