package:
    name: conmin
    version: dev

source:
    path: ../../contrib/conmin

build:
    preserve_egg_dir: yes
    
requirements:
    build:
        - python
        - setuptools
        - numpy

    run:
        - python
        - numpy
