package:
 name: openmdao.test

source:
 path:  ../../openmdao.test

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - openmdao.main
    - nose

build:
  entry_points:
    - openmdao.test.execcomp.ExecComp = openmdao.test.execcomp:ExecComp
    - nosetimerplugin = openmdao.test.nosetimer:TestTimer
    - nosesummaryplugin = openmdao.test.testing:TestFailureSummary
    - noseearlyplugin = openmdao.test.early_report:EarlyTestInfo

about:
  home:  http://openmdao.org
  license:  Apache 2.0
  summary:  "Open-source Multidisciplinary Design, Analysis and Optimazation framework in Python."
