package:
    name: cobyla
    version: !!str {{ environ['PKG_VERSION'] }}

source:
    path: ../../contrib/cobyla

build:
    preserve_egg_dir: True

requirements:
    build:
        - python
        - setuptools
        - numpy

    run:
        - python
        - numpy
