package:
    name: openmdao
    version: !!str 0.12.0

requirements:
    run:
        # Core
        - openmdao.lib ==0.12.0
        - openmdao.main ==0.12.0
        - openmdao.units ==0.12.0
        - openmdao.util ==0.12.0
        - openmdao.test ==0.12.0

        # Examples
        - openmdao.examples.bar3simulation ==0.12.0
        - openmdao.examples.expected-improvement ==0.12.0
        - openmdao.examples.mdao ==0.12.0
        - openmdao.examples.metamodel-tutorial ==0.12.0
        - openmdao.examples.nozzle-geometry-doe ==0.12.0
        - openmdao.examples.simple ==0.12.0

        # Fortran Extensions
        - cobyla ==1.0.2
        - conmin ==1.0.2
        - slsqp ==1.0.2
        - newsumt ==1.1.1

        # Dependencies
        - bson ==0.3.3
        - decorator ==3.4.0
        - docutils ==0.10
        - jinja2 ==2.4
        - mock ==1.0.1
        - networkx ==1.9.1
        - nose ==1.3.3
        - numpy
        - pycrypto ==2.3
        - pyevolve ==0.6
        - pygments ==1.3.1
        - pyparsing ==1.5.7
        - pytz ==2011k
        - requests ==2.2.1
        - scipy
        - setupDocs ==1.0.5
        - sphinx ==1.2.2 
        - traits ==4.3.0
        - zope.interface ==3.6.1  

