package:
    name: cobyla
    version: dev

source:
    path: ../../contrib/cobyla

requirements:
    build:
        - python
        - setuptools
        - numpy

    run:
        - python
        - numpy
