package:
    name: slsqp
    version: dev

source:
    path: ../../contrib/slsqp

build:
    preserve_egg_dir: no
    
requirements:
    build:
        - python
        - setuptools
        - numpy
    
    run:
        - python
        - numpy
