package:
    name: slsqp
    version: dev

source:
    path: ../../contrib/slsqp

requirements:
    build:
        - python
        - setuptools
        - numpy
    
    run:
        - python
        - numpy
