package:
    name: openmdao.examples.simple
    version: dev
    
source:
    path: ../../examples/openmdao.examples.simple

build:
    preserve_egg_dir: yes
    
requirements:
    build:
        - python
        - setuptools
        - openmdao.main
        - openmdao.lib
        
    run:
        - python
        - setuptools
        - openmdao.main
        - openmdao.lib
