package:
    name: bson
    version: dev

source:
    git_url: https://github.com/martinkou/bson.git

requirements:
    build:
        - python
        - setuptools
        - pytz >=2010b

    run:
        - python
