package:
    name: newsumt
    version: dev

source:
    path: ../../contrib/newsumt

requirements:
    build:
        - python
        - setuptools
        - numpy

    run:
        - python
        - numpy
