package:
    name: newsumt
    version: dev

source:
    path: ../../contrib/newsumt

build:
    preserve_egg_dir: True
    
requirements:
    build:
        - python
        - setuptools
        - numpy

    run:
        - python
        - numpy
