package:
 name: openmdao.devtools

source:
 path:  ../../openmdao.devtools

requirements:
  build:
    - python
    - setuptools
    
  run:
    - python
    - setuptools
    - sphinx
    - fabric >=0.9.3
    - openmdao.util
    - boto
    - paramiko >=1.7.7
    - requests

build:
  entry_points:
    - wingproj = openmdao.devtools.wingproj:run_wing
    - make_installer = openmdao.devtools.mkinstaller:main
    - release = openmdao.devtools.releasetools:release
    - push_dists = openmdao.devtools.push_dists:main
    - remote_build = openmdao.devtools.remote_build:main

    about:
  home:  http://openmdao.org
  license:  Apache 2.0
  summary:  "Open-source Multidisciplinary Design, Analysis and Optimazation framework in Python."
