package:
    name: openmdao.examples.mdao
    version: dev
    
source:
    path: ../../examples/openmdao.examples.mdao

build:
    preserve_egg_dir: True
    
requirements:
    build:
        - python
        - setuptools
        - openmdao.main
        - openmdao.lib
                
    run:
        - python
        - setuptools
        - openmdao.main
        - openmdao.lib
