package:
    name: slsqp
    version: !!str 1.0.2

source:
    path: ../../contrib/slsqp

build:
    preserve_egg_dir: True

requirements:
    build:
        - python
        - setuptools
        - numpy
        - libgfortran #[osx]

    run:
        - python
        - numpy
        - libgfortran #[osx]
