package:
    name: slsqp
    version: !!str {{ environ['PKG_VERSION'] }}

source:
    path: ../../contrib/slsqp

build:
    preserve_egg_dir: True

requirements:
    build:
        - python
        - setuptools
        - numpy ==1.7.1

    run:
        - python
        - numpy >=1.7.1
        - libpython
